In [33]:
pip install numpy # to install the requirements 

Note: you may need to restart the kernel to use updated packages.


ERROR: Invalid requirement: '#': Expected package name at the start of dependency specifier
    #
    ^


In [34]:
import numpy as np # importing the numpy 

In [ ]:
arr1=np.array([]) # creating the empty NumPy array
arr1

array([], dtype=float64)

In [ ]:
l1=[] # creating a Empty list
l1

[]

In [49]:
my_list=[1,2,3,45,6]
print(my_list)
print(type(my_list))

[1, 2, 3, 45, 6]
<class 'list'>


In [50]:
a=np.array(my_list) # converting the list in to NumPyarray 

In [51]:
a # displaying the data of the array 

array([ 1,  2,  3, 45,  6])

In [52]:
my_list+[2,3] # concatenation the list

[1, 2, 3, 45, 6, 2, 3]

In [55]:
type(a) # to see the type 

numpy.ndarray

In [57]:
a.ndim # to see the dimession 

1

In [58]:
a.size # to see the size 

5

In [60]:
a.shape # to see the shape 

(5,)

In [65]:
print(type(a))
b=a.tolist()
print(type(b))

<class 'numpy.ndarray'>
<class 'list'>


In [67]:
a=np.array(b)

## Arrays can be of n dimensions 

In [71]:
my_matrix=[100,200,300,400,500]
print(my_matrix)
matrix=np.array(my_matrix)
print(matrix)
print("dimensions of matrix:",matrix.ndim)
print("type of the array:",type(matrix))
print("shape of the array:",matrix.shape)
print("size of the array :",matrix.size)
b=matrix.tolist()
print(type(b))

[100, 200, 300, 400, 500]
[100 200 300 400 500]
dimensions of matrix: 1
type of the array: <class 'numpy.ndarray'>
shape of the array: (5,)
size of the array : 5
<class 'list'>


In [75]:
b[3]

400

In [78]:
arr2=np.array(["this","is"])
arr2

array(['this', 'is'], dtype='<U4')

In [79]:
np.mean([1,2,3,4,5,6])

np.float64(3.5)

## built -in methods 

In [88]:
arr1=np.arange(0,27).reshape(3,3,3)

In [89]:
arr1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [90]:
arr1.shape

(3, 3, 3)

In [91]:
arr2=arr1.reshape(arr1.shape)

In [92]:
arr2

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [97]:
arr2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Arange

In [99]:
t=45,35,36
type(t)

tuple

In [100]:
t

(45, 35, 36)

In [101]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [102]:
np.arange(2,15)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [103]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [104]:
np.zeros(3)

array([0., 0., 0.])

In [107]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [112]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [113]:
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

linspace

In [115]:
np.linspace(1,15)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [116]:
np.linspace(5,25,10,retstep=True)

(array([ 5.        ,  7.22222222,  9.44444444, 11.66666667, 13.88888889,
        16.11111111, 18.33333333, 20.55555556, 22.77777778, 25.        ]),
 np.float64(2.2222222222222223))

In [117]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [118]:
np.eye(5,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [119]:
np.random.rand()

0.15992461759322474

In [120]:
np.random.rand(10)

array([0.30563878, 0.6349704 , 0.562174  , 0.44607494, 0.50221993,
       0.99111731, 0.6315632 , 0.33618759, 0.57682925, 0.84457988])

In [125]:
arr=np.random.rand(5,2)

In [126]:
arr

array([[0.24647249, 0.7505943 ],
       [0.14122801, 0.09805358],
       [0.06947276, 0.79873557],
       [0.6580605 , 0.90455333],
       [0.21026549, 0.96345662]])

In [127]:
np.mean(arr)

np.float64(0.4840892654469887)

In [128]:
np.std(arr)

np.float64(0.3430454390851058)

In [129]:
np.var(arr)

np.float64(0.11768017327709306)

In [130]:
np.median(arr)

np.float64(0.45226649345089004)