In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import sklearn 
import warnings
warnings.filterwarnings("ignore")

In [2]:
data={
    "EmployeeId":[101,102,103,104,105],
    "Salary":[30000,4000,5000,30000,40000],
    "Name":["Sumanth","santhosh","Surendra","Mansa","Bhargavi"]
}
pf=pd.DataFrame(data)
print(pf)

   EmployeeId  Salary      Name
0         101   30000   Sumanth
1         102    4000  santhosh
2         103    5000  Surendra
3         104   30000     Mansa
4         105   40000  Bhargavi


In [4]:
pf["Salary"]

0    30000
1     4000
2     5000
3    30000
4    40000
Name: Salary, dtype: int64

In [11]:
pf.loc[:,["Salary","Name"]]

,Salary,Name
0,30000,Sumanth
1,4000,santhosh
2,5000,Surendra
3,30000,Mansa
4,40000,Bhargavi


In [ ]:
# Numpy 
# pip install numpy 
import numpy as np 
arr1=np.array([])
print(arr1) # displaying the empty array
arr2=[100,200,300,400] # craeting the list 
df=np.array(arr2) # coverting the list in to np array 
print(df)# printing the np array 
# we have to check the type of the array 
print(type(df))
# We are checking the dimension of the array 
print(df.ndim) # it has only one dimension 
# printing the size of the array 
print(df.size) # the size of the array id 4
# checking the shape of the array 
print(df.shape) # the shape 4
# concatenating the list 
arr2+[200] # adding the data to existing list 
# checking the datatype 
print(df.dtype) # the datatype is int64
# we have to check the mean of the array 
print(np.mean(df)) # the mean is 250
# reshapping 
print(df.reshape(2,2)) # we reshape to 2 rows to two columns 
# flatten function it use to convert the n dimenssional array in to one dimensional array 
print(df.flatten()) # its converted 
#Arange concept 
print(np.arange(15))
print(np.arange(2,100,10)) # three are same with small difference we know that difference 
print(np.arange(2,50))
# we want to print one d array with zeros 
print(np.zeros(3))
print(np.zeros((1,10)))
# we can ones with n dimenssional 
print(np.ones((2,5,6)))
# lines space 
print(np.linspace(1,15))
print(np.linspace(2,25,10,retstep=True))
# creatig the identity matrix
print(np.eye(2,2))
# boarding casting 
print(df+6)
# copy 
pf=df.copy() # copy function retains the original copy and creates the backup 
print(pf)
# random numbers 
print(np.random.rand(2,2))

[]
[100 200 300 400]
<class 'numpy.ndarray'>
1
4
(4,)
int64
250.0
[[100 200]
 [300 400]]
[100 200 300 400]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2 12 22 32 42 52 62 72 82 92]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]
[ 1.          1.28571429  1.57142857  1.85714286  2.14285714  2.42857143
  2.71428571  3.          3.28571429  3.57142857  3.85714286  4.14285714
  4.42857143  4.71428571  5.          5.28571429  5.57142857  5.85714286
  6.14285714  6.42857143  6.71428571  7.          7.28571429  7.57142857
  7.85714286  8.14285714  8.42857143  8.71428571  9.          9.28571429
  9.57142857  9.85714286 10.14285

array([[0.24346251, 0.43785763],
       [0.40794106, 0.51619252]])

In [ ]:
print(np.random.randint(1,2000,10))
print(np.random.randn(2,3,1))


[ 559 1628  396 1282 1260  144  394  984  922  633]
