In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import sklearn 
import warnings
warnings.filterwarnings("ignore")

In [2]:
data={
    "EmployeeId":[101,102,103,104,105],
    "Salary":[30000,4000,5000,30000,40000],
    "Name":["Sumanth","santhosh","Surendra","Mansa","Bhargavi"]
}
pf=pd.DataFrame(data)
print(pf)

   EmployeeId  Salary      Name
0         101   30000   Sumanth
1         102    4000  santhosh
2         103    5000  Surendra
3         104   30000     Mansa
4         105   40000  Bhargavi


In [4]:
pf["Salary"]

0    30000
1     4000
2     5000
3    30000
4    40000
Name: Salary, dtype: int64

In [11]:
pf.loc[:,["Salary","Name"]]

,Salary,Name
0,30000,Sumanth
1,4000,santhosh
2,5000,Surendra
3,30000,Mansa
4,40000,Bhargavi


In [ ]:
# Numpy 
# pip install numpy 
import numpy as np 
arr1=np.array([])
print(arr1) # displaying the empty array
arr2=[100,200,300,400] # craeting the list 
df=np.array(arr2) # coverting the list in to np array 
print(df)# printing the np array 
# we have to check the type of the array 
print(type(df))
# We are checking the dimension of the array 
print(df.ndim) # it has only one dimension 
# printing the size of the array 
print(df.size) # the size of the array id 4
# checking the shape of the array 
print(df.shape) # the shape 4
# concatenating the list 
arr2+[200] # adding the data to existing list 
# checking the datatype 
print(df.dtype) # the datatype is int64
# we have to check the mean of the array 
print(np.mean(df)) # the mean is 250
# reshapping 
print(df.reshape(2,2)) # we reshape to 2 rows to two columns 
# flatten function it use to convert the n dimenssional array in to one dimensional array 
print(df.flatten()) # its converted 
#Arange concept 



[]
[100 200 300 400]
<class 'numpy.ndarray'>
1
4
(4,)
int64
250.0
[[100 200]
 [300 400]]
[100 200 300 400]
