NumPy 

In [3]:
import numpy as np

In [4]:
Sum=np.array([10,20,30,40,50]) # Creating a numpy array and printing the array
print(Sum)

[10 20 30 40 50]


N- Dimensional Arrays

In [5]:
x=np.array([1,2,3,4,5]) #1D array
print(x)

[1 2 3 4 5]


In [6]:
y=np.array([[1,2,3,4],[1,2,3,4]]) # 2D array
print(y)

[[1 2 3 4]
 [1 2 3 4]]


In [8]:
su=np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]]]) #3D array
print(su)

[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [4 5 6]]]


## Why Arrays instead of list

* Faster 
* Less memory usage 
* vectorized operations
* supports advanced mathematics 

In [ ]:
Numbers=[10,20,30,40] # normal list
print(Numbers)

[10, 20, 30, 40]


In [ ]:
Numbers=np.array([10,20,30,40]) # creating list with the NumPy array
print(Numbers)

[10 20 30 40]


In [12]:
np.zeros((3,4)) # creating an array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((3,4)) # creating an array of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.eye(3) # creating an identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.arange(1,11) # creating range of numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.arange(2,11,2) # creating range of numbers with step size

array([ 2,  4,  6,  8, 10])

In [18]:
np.linspace(0,10,5) # creating range of numbers with evenly spaced numbers 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Ramdom variables 

In [19]:
np.random.randint(1,100,10) # creating random numbers between 1 and 100 with 10 numbers 

array([49, 73, 50, 40, 34, 32, 61, 48,  9, 55], dtype=int32)

## Ramdom Numbers

In [20]:
np.random.rand(5) # creating random numbers between 0 and 1 with 5 numbers 

array([0.63861453, 0.17316074, 0.58585075, 0.28698385, 0.07475902])

## Random matrix

In [21]:
np.random.rand(3,3) # creating random numbers between 0 and 1 with 3 rows and 3 columns 

array([[0.10322415, 0.78653225, 0.40544396],
       [0.26747233, 0.48058445, 0.08288977],
       [0.89174614, 0.27695671, 0.66040683]])

## Array Attributes 

In [22]:
sum1=np.array([[1,2,3],[2,3,4]])

In [24]:
sum1.shape # for getting the shape of the array 

(2, 3)

In [25]:
sum1.ndim # for getting the dimension of the array 

2

In [26]:
sum1.size # for getting the size of the array 

6

In [27]:
sum1.dtype # for the data type of the array 

dtype('int64')

## Mathematical operations 

In [29]:
sum1 +10  # addtion

array([[11, 12, 13],
       [12, 13, 14]])

In [30]:
sum1 *10 # multiplication 

array([[10, 20, 30],
       [20, 30, 40]])

In [31]:
sum1/2 # division 

array([[0.5, 1. , 1.5],
       [1. , 1.5, 2. ]])

In [32]:
sum1 ** 200 # squaring the array 

array([[                  1,                   0, 6627890308811632801],
       [                  0, 6627890308811632801,                   0]])

In [33]:
np.sqrt(sum1) # square root of the array 

array([[1.        , 1.41421356, 1.73205081],
       [1.41421356, 1.73205081, 2.        ]])

## Statistical Functions 

In [34]:
Sum2=np.array([10,20,30,40])

In [36]:
Sum2.mean() # mean of the array 

np.float64(25.0)

In [37]:
Sum2.sum() # sum of the array 

np.int64(100)

In [38]:
Sum2.max() # maximum value of the array 

np.int64(40)

In [39]:
Sum2.min() # minimum value of the array 

np.int64(10)

In [40]:
Sum2.std() # stamdard deviation of the array

np.float64(11.180339887498949)

In [42]:
np.median(Sum2) # median of the array 

np.float64(25.0)

## Array Indexing 

In [43]:
sum1=np.array([20,30,40,50,40])

In [45]:
sum1[0] # acessing the first element of the array 

np.int64(20)

In [46]:
sum1[-1] # acessing the last element of the array

np.int64(40)

In [47]:
sum1[1:4] # Sliceing of the array

array([30, 40, 50])

## 2D indexing 

In [48]:
sum3=np.array([[1,2,3,4],[5,6,7,8],[2,4,4,5]])

In [ ]:
sum3[1,1] # acessing elements of the 2D array

np.int64(6)

In [51]:
sum3[1] # acessing entre row 

array([5, 6, 7, 8])

In [54]:
sum3[:,1] # acessing entire column

array([2, 6, 4])

## Reshaping arrays

In [57]:
sum=np.arange(12) # creating a range array 

In [58]:
sum.reshape(3,4) # reshaping the array 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## filtering array


In [59]:
arr=np.arange(50) 

In [60]:
arr[arr> 25]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])