## SciPy:

In [2]:
import scipy 

## importing specific model 

In [4]:
from scipy import stats ## statistics and probability 
from scipy import optimize ## find the best solution
from scipy import linalg ## linear algebra 

In [6]:
data=[10,20,30,40,50]
print(stats.tmean(data)) ## printing mean using SciPy

30.0


In [9]:
data=[1,2,2,3,4]
print(stats.mode(data)) ## print mode using SciPy

ModeResult(mode=np.int64(2), count=np.int64(2))


In [11]:
import numpy as np
data=np.array([10,20,30,40,50])
print(np.std(data))  ## printing standard Deviation using numpy 

14.142135623730951


## Probability Distributins 

In [12]:
from scipy.stats import norm
data=norm.rvs(size=5)
print(data)

[-2.63291796  0.19713557 -0.75244327  1.12439291 -0.79465127]


## Hypothesis Testing 

In [13]:
from scipy.stats import ttest_1samp
data=[72,75,78,80,85]
t_stat,p_value=ttest_1samp(data,70)
print(t_stat)
print(p_value)


3.614031611621005
0.022475959165885552


## Optimization

In [14]:
from scipy.optimize import minimize 
def func(x):
    return x**2+5
result=minimize(func,x0=10)
print(result.x)

[-6.16406142e-08]


## Linear Algebra 

In [15]:
from scipy import linalg 

In [16]:
import numpy as np
A=np.array([[1,2],[3,4]])

In [17]:
print(linalg.det(A)) ## Determinate 

-2.0


In [ ]:
print(linalg.inv(A)) ## inverse

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
values,vectors=linalg.eig(A)
print(values)
print(vectors)  ## Eigenvalues

[-0.37228132+0.j  5.37228132+0.j]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## Numerical integration 

In [20]:
from scipy.integrate import quad
def f(x):
    return x**2
result,error=quad(f,0,2)
print(result)

2.666666666666667


## Interpolation

In [21]:
from scipy.interpolate import interp1d
x=[1,2,3,4]
y=[10,20,30,40]
f=interp1d(x,y)
print(f(2.5))

25.0


## Distance calculations

In [22]:
from scipy.spatial.distance import euclidean
a=[1,2]
b=[4,6]
print(euclidean(a,b))

5.0


## Signal processing 

In [25]:
from scipy import signal
signal.medfilt([1,2,100,3,4])  ## its just an example ::this remove the noise data

array([1, 2, 3, 4, 3])

In [28]:
import pandas as pd
from  scipy import stats
df=pd.read_excel("D:\Sumanth.xlsx") 
marks=df["Marks"]
print("mean:",stats.tmean(marks))
print("mode:",stats.mode(marks))


mean: nan
mode: ModeResult(mode=np.float64(65.0), count=np.int64(3))
